name: "Add Milestone"
description: "Add a milestone to a merged PR"
inputs:
  token:
    description: "GitHub access token"
    required: true
    default: ""
runs:
  using: node12
  main: "src/index.js"
